### PR TITLE
Added error code '-2' : ENOENT : No such file or directory

### PR DESCRIPTION
**Pull request by ClementNerma**
I added error code '-2' : ENOENT : No such file or directory

### CODE REVIEW

**Comment by wkl** [comment]
Is it duplicate with the ENOENT on errno: 34?
Why is it "errorno: -2" instead of "errno: -2"?

**Comment by ClementNerma** [comment]
Yes, error code -2 is duplicate with the 34, but when Node-WebKit emit a ENOENT error, the code returned is -2.
(Oops, I did a mistake, that's "errno: -2"

**Comment by lukaaash** [comment]
On Node.js 0.12.7, I get -2 for ENOENT as well. But on Windows, I get -4058.
Code to reproduce this:
    `require('fs').readFile('/invalid-path/no-file', function (e) { console.log(e) })`

**Comment by ClementNerma** [comment]
I don't have Windows on my computer, so I can't test it...

**Pull request merged**
